version: '3.9'
services:
  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    command:
      - --dev
      - --reload
    environment:
      # FOR APPLICATION
      - MODE=${MODE:-production}
      # FOR VERIFICATION
      - VERIFY_REQUEST_URL=${VERIFY_REQUEST_URL:-https://laozi-testnet6.bandchain.org/api/oracle/v1/verify_request}
      - ALLOWED_DATA_SOURCE_IDS=${ALLOWED_DATA_SOURCE_IDS:-}
      - CACHE_SIZE=${CACHE_SIZE:-1000}
      # FOR ADAPTER
      - ADAPTER_TYPE=${ADAPTER_TYPE:-}
      - ADAPTER_NAME=${ADAPTER_NAME:-}
      # FOR CALLING API
      - API_KEY=${API_KEY:-}
    volumes:
      - .:/app
