version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.0.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install --no-root
      - run: poetry run pytest
      - setup_remote_docker:
          version: 20.10.18
      - run: |
          docker build -t gcr.io/${GOOGLE_CLOUD_PROJECT}/${SERVICE_NAME} .

  deploy:
      executor: gcp-cli/default
      steps:
      - gcp-cli/install
      - gcp-cli/initialize
      - run: |
          gcloud auth application-default print-access-token | \
          gcloud auth activate-service-account --key-file=-
      - run: |
          gcloud --quiet run deploy my-service \
            --image gcr.io/${GOOGLE_CLOUD_PROJECT}/${SERVICE_NAME} \
            --region ${GOOGLE_CLOUD_REGION} \
            --platform managed \
            --allow-unauthenticated

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
            requires:
              - build
