name: Run Tests
on: pull_request

jobs:
  test-pds-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Test PDS Gateway
        run: |-
          pip3 install poetry
          poetry config virtualenvs.create false
          poetry install --no-root
          poetry run pytest
        working-directory: .
