jobs:
  test-pds-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade build tools 
        run: |
          pip install --upgrade pip setuptools packaging wheel

      - name: Test PDS Gateway
        run: |-
          pip3 install poetry
          poetry config virtualenvs.create false
          poetry install --no-root
          poetry run pytest
        working-directory: .
