jobs:
  test-pds-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Test PDS Gateway
        run: |-
          pip3 install --upgrade pip3 setuptools packaging wheel
          pip3 install --upgrade poetry  # Get latest Poetry
          poetry config virtualenvs.create false
          poetry install --no-root
          poetry run pytest
        working-directory: .
